spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.mvc.routes[0].id=user-service
spring.cloud.gateway.mvc.routes[0].uri=lb://user-service
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/api/users/**,/api/auth/**

spring.cloud.gateway.mvc.routes[1].id=movie-service
spring.cloud.gateway.mvc.routes[1].uri=lb://movie-service
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/api/movies,/api/movies/**

spring.cloud.gateway.mvc.routes[2].id=booking-availability
spring.cloud.gateway.mvc.routes[2].uri=lb://booking-service
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/api/shows/*/availability

spring.cloud.gateway.mvc.routes[3].id=show-service
spring.cloud.gateway.mvc.routes[3].uri=lb://show-service
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/api/screens/**,/api/shows/**

spring.cloud.gateway.mvc.routes[4].id=booking-service
spring.cloud.gateway.mvc.routes[4].uri=lb://booking-service
spring.cloud.gateway.mvc.routes[4].predicates[0]=Path=/api/bookings/**
